### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by xhzq233** [7sDream/danmacu#5]
如下
```
danmacu-master python -m danmacu.main 23679661
Danmaku page: http://127.0.0.1:7777/index.html
Press Command+C to stop...
人气 = 1
Traceback (most recent call last):
  File "/Users/xhz/danmacu-master/danmacu/danmaku_client.py", line 41, in __worker
    for packet in Packet.parse(message):
  File "/Users/xhz/danmacu-master/danmacu/packet.py", line 55, in parse
    packet = cls.parse_one(message, offset)
  File "/Users/xhz/danmacu-master/danmacu/packet.py", line 44, in parse_one
    tag) = struct.unpack_from(">ihhii", message, offset)
struct.error: unpack_from requires a buffer of at least 36 bytes for unpacking 16 bytes at offset 20 (actual buffer size is 35)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xhz/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/xhz/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/xhz/danmacu-master/danmacu/main.py", line 53, in <module>
    main()
  File "/Users/xhz/danmacu-master/danmacu/main.py", line 49, in main
    asyncio.get_event_loop().run_until_complete(asyncio.gather(*tasks))
  File "/Users/xhz/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/xhz/danmacu-master/danmacu/server.py", line 45, in start
    await asyncio.gather(super().start(), self.listen())
  File "/Users/xhz/danmacu-master/danmacu/danmaku_client.py", line 92, in start
    await self.__worker(self._appkey, self._secret, self._room_id)
  File "/Users/xhz/danmacu-master/danmacu/danmaku_client.py", line 89, in __worker
    await ws.start(self)
  File "/Users/xhz/danmacu-master/danmacu/danmaku_client.py", line 64, in start
    await DanmakuWebsocketClient.__worker(client, self._room)
  File "/Users/xhz/danmacu-master/danmacu/danmaku_client.py", line 61, in __worker
    await client.on_error(e)
  File "/Users/xhz/danmacu-master/danmacu/server.py", line 79, in on_error
    print(error.message)
AttributeError: 'error' object has no attribute 'message'
```

**Comment by 7sDream** [comment]
Close due to #6 should fix this.
